# 0x05. Python - Exceptions

0- Function that prints x elements of a list. x represents the number of elements to print; x can be bigger than the length of my_list; Returns the real number of elements printed

1- Function that prints an integer with "{:d}".format(). Returns True if value has been correctly printed (it means the value is an integer) Otherwise, returns False

2- Function that prints the first x elements of a list and only integers. x represents the number of elements to access in my_list; x can be bigger than the length of my_list - if it’s the case, an exception will occur; Returns the real number of integers printed

3- Function that divides 2 integers and prints the result. The result of the division should print on the finally: section preceded by Inside result: Returns the value of the division, otherwise: None

4- Function that divides element by element 2 lists. Returns a new list (length = list_length) with all divisions
If 2 elements can’t be divided, the division result should be equal to 0
If an element is not an integer or float:
print: wrong type
If the division can’t be done (/0):
print: division by 0
If my_list_1 or my_list_2 is too short
print: out of range

5- Function that raises a type exception. 

6- Function that raises a name exception with a message.

100- Function that prints an integer. Returns True if value has been correctly printed (it means the value is an integer); Otherwise, returns False and prints in stderr the error precede by Exception:

101- Function that executes a function safely. Returns the result of the function, Otherwise, returns None if something happens during the function and prints in stderr the error precede by Exception:

