The ``101-lazy_matrix_mul`` module
======================

Using ``lazy_matrix_mul``
-------------------

First import
``lazy_matrix_mul`` from the ``101-lazy_matrix_mul`` module:

    >>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Now use it:

    >>> m_a = [[1, 2], [3, 4]]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(m_a, m_b)
    array([[ 7, 10],
      	   [15, 22]])


    >>> m_a = [[1, 2], [3, 4], 6]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    ValueError: setting an array element with a sequence.

    >>> m_a = [[1, 2], [3, 4]]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(2, m_b)
    Traceback (most recent call last):
        ...
    ValueError: Scalar operands are not allowed, use '*' instead


    >>> m_a = [[1, "Holberton"], [3, 4]]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    TypeError: invalid data type for einsum

    >>> m_a = [[1, 2], [3, 4], [3, 4, 5]]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    ValueError: setting an array element with a sequence.

    >>> m_a = [[1, 2], [3, 4]]
    >>> m_b = [[1, 2], [3, 4], [3, 4, 5]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    ValueError: setting an array element with a sequence.

    >>> m_a = [[1, 2], [3, 4]]
    >>> m_b = [[1, 2], [3, 4], [5, 6]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

    >>> m_a = [[1, 2], [3, 4]]
    >>> m_b = [[]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
    ...
    ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

    >>> m_a = [[]]
    >>> m_b = [[1, 2], [3, 4]]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
        ...
    ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

    >>> m_a = [[]]
    >>> m_b = [[]]
    >>> lazy_matrix_mul(m_a,)
    Traceback (most recent call last):
        ...
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

    >>> lazy_matrix_mul()
    Traceback (most recent call last):
        ...
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
